node {

    def dockerImage

    step([$class: 'WsCleanup'])

    stage('Checkout scm') {
        checkout scm
    }

    stage('Run test') {
        dir ('movie-analyst-api') {
            docker.image('node:10.11.0-alpine').inside {
                echo 'Performing tests'
                sh 'npm install'
                sh 'npm test'
            }
        }
    }

    stage('Build docker image') {
        dir ('movie-analyst-api') {
            echo "Building docker image"
            dockerImage = docker.build("manuel11coral23/my-node-js-image")
        }
    }

    stage('Publish docker image') {
        docker.withRegistry("https://index.docker.io/v1/", 'docker-hub') {
            dockerImage.push("$BUILD_NUMBER")
        }
    }
}