node {
    stage('Checkout scm') {
        checkout scm
    }

    stage('Run test') {
        docker.image('node:10.11.0-alpine').withRun().inside() {
            echo 'Performing tests'
            sh 'node server.js'
            //sh 'npm test'
        }
    }

    stage('Build docker image') {
        echo "Not yet"
    }
}